apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: externalpool
spec:
  cidrs:
    - cidr: 192.168.100.0/28
  disabled: false
  serviceSelector:
    matchLabels:
      exposedExternal: "yes"
