apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: opnsense
spec:
  nodeSelector:
    matchLabels:
      peering: "yes"
  virtualRouters:
    - localASN: 65001
      neighbors:
        - peerASN: 65000
          peerAddress: 10.20.0.1/32
      serviceSelector:
        matchLabels:
          exposedExternal: "true"

