---
# - name: install cilium on main
#   hosts: main
#   become: true
#   tasks:
#     - name: install cilium on main
#       script: scripts/cilium-install.sh


- name: install cilium on main
  hosts: main 
  become: true 
  tasks:
    - name: Add cilium chart repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"
    - name: install cilium cli and cilium
      kubernetes.core.helm: 
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        # release_namespace: cilium-system
        state: absent
        wait: true
      register: cilium_uninstall_main_logs
    - name: print cilium_uninstall_main_logs output
      debug: 
        msg: "{{ cilium_uninstall_main_logs.stdout_lines }}"
    - name: print cilium_uninstall_main_logs errors
      debug: 
        msg: "{{ cilium_uninstall_main_logs.stderr_lines }}"

# - name: install cilium-cli on members
#   hosts: members
#   become: true 
#   tasks:
#     - name: install cilium-cli only
#       shell: |
#         CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
#         CLI_ARCH=amd64
#         if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
#         curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
#         sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
#         sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
#         rm cilium-linux-${CLI_ARCH}.tar.gz
#         rm cilium-linux-${CLI_ARCH}.tar.gz.sha256sum

#         export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
#       register: cilium_install_member_logs
#     - name: print cilium_install_member_logs
#       debug: 
#         msg: "{{ cilium_install_member_logs }}"
