all:
  hosts:
  children:
    main:
      hosts:
        10.20.0.90:
    members:
      hosts:
        10.20.0.91:
        10.20.0.92:
  vars:
    ansible_user: ansible
    _vip: 10.20.0.99
    _interface: eth0
    _clustercidr: 10.42.0.0/16
    _podcidr: 10.42.0.0/16
    _longhornversion: 1.5.1
    _k8sServiceHost: 10.20.0.90
    _k8sInitialMasterHostname: k8s-master-0-dev
