---

- name: Prepare files required for kube-vip
  hosts: all
  become: true
  tasks:
    - name: Create /var/lib/rancher directory
      file:
        path: /var/lib/rancher
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Create /var/lib/rancher/k3s directory
      file:
        path: /var/lib/rancher/k3s
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Create /var/lib/rancher/k3s/server directory
      file:
        path: /var/lib/rancher/k3s/server
        state: directory
        owner: root
        group: root
        mode: '0700'
    - name: Create /var/lib/rancher/k3s/server/manifests directory
      file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory
        owner: root
        group: root
        mode: '0700'
    - name: download rbac yaml
      shell: curl https://kube-vip.io/manifests/rbac.yaml > /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
    - name: create kube-vip-ds.yaml file
      file:
        path: /var/lib/rancher/k3s/server/manifests/kube-vip-ds.yaml
        state: touch
        owner: root
        group: root
        mode: '0644'
    - name: update .bashrc
      blockinfile:
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-ds.yaml
        content: |
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            creationTimestamp: null
            name: kube-vip-ds
            namespace: kube-system
          spec:
            selector:
              matchLabels:
                name: kube-vip-ds
            template:
              metadata:
                creationTimestamp: null
                labels:
                  name: kube-vip-ds
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: node-role.kubernetes.io/master
                          operator: Exists
                      - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: Exists
                containers:
                - args:
                  - manager
                  env:
                  - name: vip_arp
                    value: "true"
                  - name: port
                    value: "6443"
                  - name: vip_interface
                    value: eth0
                  - name: vip_cidr
                    value: "32"
                  - name: cp_enable
                    value: "true"
                  - name: cp_namespace
                    value: kube-system
                  - name: vip_ddns
                    value: "false"
                  - name: svc_enable
                    value: "true"
                  - name: vip_leaderelection
                    value: "true"
                  - name: vip_leaseduration
                    value: "5"
                  - name: vip_renewdeadline
                    value: "3"
                  - name: vip_retryperiod
                    value: "1"
                  - name: address
                    value: 10.20.0.99
                  image: ghcr.io/kube-vip/kube-vip:v0.6.0
                  imagePullPolicy: Always
                  name: kube-vip
                  resources: {}
                  securityContext:
                    capabilities:
                      add:
                      - NET_ADMIN
                      - NET_RAW
                      - SYS_TIME
                hostNetwork: true
                serviceAccountName: kube-vip
                tolerations:
                - effect: NoSchedule
                  operator: Exists
                - effect: NoExecute
                  operator: Exists
            updateStrategy: {}
          status:
            currentNumberScheduled: 0
            desiredNumberScheduled: 0
            numberMisscheduled: 0
            numberReady: 0
