apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: luigi.francisco@gmail.com
    # Prod 
#    server: https://acme-v02.api.letsencrypt.org/directory
    # We use the staging server here for testing to avoid hitting
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it 
      name: letsencrypt-acc-key
    solvers:
      - dns01:
      # The ingressClass used to create the necessary ingress routes
#          ingress:
#            ingressClassName: nginx
          cloudflare:
            email: luigi.francisco@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: apiToken
        selector:
          dnsZones:
            - 'su-root.net'
#          dnsNames:
#           - 'example.com'
#            - 'nginx.su-root.net'
#            - '*.su-root.net'
#          dnsZones:
#            - '*.su-root.net'
